package enums;

public enum Rango {
    COMANDANTE, SEGUNDO_COMANDANTE, TERCER_COMANDANTE, CAPITAN, SEGUNDO_CAPITAN, TERCER_CAPITAN,
    PRIMER_OFICIAL, SEGUNDO_OFICIAL, PILOTO_INSTRUMENTAL, ALUMNO_PILOTO
}
